angular.module('app').config(['$stateProvider', '$urlRouterProvider',function($stateProvider,$urlRouterProvider){
    $stateProvider
    .state('main',{
        url:'/main',
        templateUrl:'view/main.html',
        controller:'mainCtrl'
    }).
    state('position',{
        url:'/position/:id',
        templateUrl:'view/position/position.html',
        controller:'positionCtrl'
    }).
    state('company',{
        url:'/company/:id',
        templateUrl:'view/company/companyInfo.html',
        controller:'companyCtrl'
    }).
    state('search',{
        url:'/search',
        templateUrl:'view/search/index.html',
        controller:'seaCtrl'
    }).
    state('login',{
        url:'/login',
        templateUrl:'view/home.html',
        controller:'homeCtrl'
    }).
    state('reg',{
        url:'/reg',
        templateUrl:'view/reg.html',
        controller:'regCtrl'
    }).
    state('addCompany',{
        url:'/addCompany',
        templateUrl:'view/work-part/main.html',
        controller:'workPartCtrl'
    }).
    state('mostPage',{
        url:'/mostPage',
        templateUrl:'view/work-part/most-page.html',
        controller:'mostpageCtrl'
    }).
    state('pushJob',{
        url:'/pushJob',
        templateUrl:'view/work-part/pushJob.html',
        controller:'pushJobCtrl'
    }).
    state('ourinfo',{
        url:'/ourinfo',
        templateUrl:'view/work-part/page-info.html',
        controller:'pageInfoCtrl'
    }).
    state('pushJob.newjob',{
        url:'/newjob',
        templateUrl:'view/work-part/pushJob-newJob.html',
        controller:'newJobCtrl'
    }).
    state('pushJob.jobList',{
        url:'/jobList',
        templateUrl:'view/work-part/pushJob-jobList.html',
        controller:'jobListCtrl'
    })
    $urlRouterProvider.otherwise('main')
}])